import "./mock";
import "./bambu-lan";

export type {
  AmsHint,
  AmsHintKind,
  AmsMapping,
  AmsMappingMatch,
  AmsSlotAssignment,
  AmsSlotPlan,
  AmsSlotPlanSource,
  AmsSlotStatus,
  CommandResult,
  CommandRisk,
  ConnectionState,
  DesignFilament,
  FilamentPlan,
  LiveMachineStatus,
  MachineCredentials,
  MidPrintCommand,
  PrintState,
  RemainingLayerReshapePlan,
  ReshapeAction,
} from "./types";

export {
  createMachineAdapter,
  defaultAdapterId,
  emptyAmsSlots,
  listMachineAdapters,
  midPrintCommandRisk,
  registerMachineAdapter,
  RESERVED_BAMBU_LAN_ADAPTER_ID,
  validateLanCredentials,
  type MachineAdapter,
  type MachineAdapterFactory,
  type MachineAdapterOptions,
} from "./adapter";

export { MockMachineAdapter } from "./mock";
export { BambuLanMachineAdapter } from "./bambu-lan";
export {
  BAMBU_LAN_ADAPTER_ID,
  INCOMPLETE_LAN_HINT,
  isBambuLanMqttEnabled,
  machineLanHint,
  machineLanSource,
  readBambuLanCredentials,
  readLiveCredentials,
  resolveActiveAdapterId,
  resolveMachineAdapterId,
} from "./config";
export {
  credentialsComplete,
  getMachineUiSession,
  resetMachineUiSession,
  setMachineUiSession,
} from "./session";
export {
  MACHINE_LAN_STORAGE_KEY,
  defaultMachineLanPrefs,
  parseMachineLanPrefs,
  serializeMachineLanPrefs,
} from "./prefs";
export {
  commandFromBody,
  parseFarmConfigure,
  parseMachineConfigure,
  parsePrintDoctorBody,
  parseReshapeRemainingFromBody,
  parseReshapeRemainingFromRequest,
} from "./api";
export {
  AMS_FEED_LOOP_SENTINEL,
  amsFeedLoopPhysicalSteps,
  amsHintFromReport,
  amsPhysicalStepsFor,
  detectsAmsFeedLoop,
  isAmsAutofixEnabled,
  isAmsPrintError,
  maybeAutofixAmsFeedLoop,
  trayIndexToSlot,
  type AmsAutofixResult,
} from "./ams-autofix";
export {
  AMS_HELP_GUIDE_IDS,
  amsHelpPhysicalSteps,
  buildAmsHelpGuide,
  formatAmsSlotLabel,
  isAmsHelpGuideId,
  resolveAmsHelpSlot,
  selectAmsHelpGuide,
  selectAmsHelpGuideId,
  type AmsHelpGuide,
  type AmsHelpGuideId,
  type AmsHelpSelectInput,
} from "./ams-help";
export {
  MACHINE_CAMERA_STORAGE_KEY,
  cameraDetectCallCount,
  cameraStatusLine,
  currentStubCameraFrame,
  detectFailure,
  futureLanJpegUrl,
  injectStubCameraScene,
  isCameraDetectEnabled,
  isCameraStubEnabled,
  machineMonitorPollPath,
  maybeDetectFailure,
  mockCameraFrame,
  parseCameraStubPref,
  resetCameraDetectState,
  serializeCameraStubPref,
  toCameraDetectReport,
  type CameraDetectReport,
  type CameraFailureKind,
  type CameraFrame,
  type FailureDetection,
} from "./camera";
export {
  bambuTopics,
  buildBambuCommandPayload,
  buildPushAllRequest,
  parseBambuPrintReport,
  percentToBambuSpeedLevel,
  physicalStepsForCommand,
} from "./bambu-protocol";
export {
  CONNECT_LAN_FIRST,
  MID_PRINT_CONTROL_ID,
  describeMidPrintIntent,
  disconnectedMidPrintResult,
  looksLikeMidPrintCommand,
  mapSpeedLevelToPercent,
  mapSpeedPercentToBambuTier,
  parseMidPrintCommandPhrase,
  sendMidPrintIfConnected,
  type MidPrintIntent,
} from "./mid-print-commands";
export { redactSecrets, safeErrorMessage } from "./redact";
export { getSharedMachine, isLiveMachineSelected, resetSharedMachine } from "./runtime";
export {
  DEFAULT_FARM_MACHINE_ID,
  FARM_QUEUE_NOTE,
  FARM_STORAGE_KEY,
  FarmRegistry,
  applyFarmSelection,
  defaultFarmMachine,
  defaultFarmSnapshot,
  farmCountLabel,
  getFarmRegistry,
  nextFarmStubName,
  normalizeFarmMachine,
  parseFarmMachine,
  parseFarmSnapshot,
  resetFarmRegistry,
  selectedFarmAdapterOptions,
  serializeFarmSnapshot,
  type FarmAdapterId,
  type FarmAdapterOptions,
  type FarmEnqueueAssign,
  type FarmEnqueueInput,
  type FarmJob,
  type FarmJobStatus,
  type FarmMachine,
  type FarmSnapshot,
} from "./farm";
export {
  advanceFarmJobs,
  clearDoneFarmJobs,
  createFarmJob,
  firstFreeFarmMachineId,
  listFarmJobsByMachine,
  nextFarmJobId,
  resolveFarmEnqueueMachineId,
  tickFarmJobs,
} from "./farm-queue";
export {
  DEFAULT_PACK_CLEARANCE_MM,
  DEFAULT_PACK_MARGIN_MM,
  PLATE_PACK_NOTE,
  copiesOfPart,
  footprintInsidePlate,
  footprintsOverlap,
  packOverlays,
  packPartFromBoundingBox,
  packPartFromSize,
  packPlate,
  packPlateFromBoundingBox,
  placedSize,
  placementFootprint,
  type PackFootprint,
  type PackOptions,
  type PackPart,
  type PackPlacement,
  type PackPlan,
} from "./plate-pack";
export {
  DEFAULT_FILAMENT_COST_PER_KG,
  DEFAULT_INFILL_FACTOR,
  ESTIMATE_COST_SESSION_KEY,
  FILAMENT_DENSITY_GCM3,
  PRINT_ESTIMATE_NOTE,
  aabbVolumeMm3,
  defaultCostPerKgFor,
  densityGcm3For,
  estimatePrint,
  estimatePrintFromReport,
  formatEstimateGrams,
  formatEstimateTime,
  formatPrintEstimateLine,
  parseCostPerKgMap,
  parseCostPerKgSession,
  serializeCostPerKgMap,
  type PrintEstimate,
  type PrintEstimateAssumptions,
  type PrintEstimateInput,
  type PrintEstimateVolumeSource,
} from "./print-estimate";
export {
  PRINT_DOCTOR_MEMORY_KEY,
  applyStoredDoctorMemory,
  confirmDoctorPerfect,
  emptyPrintDoctorMemory,
  findMemoryEntry,
  memoryMaterialKey,
  memoryScopeFromResult,
  memoryScopeKey,
  parsePrintDoctorMemory,
  readPrintDoctorMemory,
  rememberPerfect,
  rememberStillBad,
  serializePrintDoctorMemory,
  writePrintDoctorMemory,
  type PrintDoctorMemoryEntry,
  type PrintDoctorMemoryScope,
  type PrintDoctorMemoryStore,
} from "./print-doctor-memory";
export {
  PROJECT_PACK_EMPTY_ERROR,
  PROJECT_PACK_FILES,
  PROJECT_PACK_NOTE,
  SHOPPING_SEARCH_TERMS,
  ProjectPackError,
  assertCanBuildProjectPack,
  buildProjectPack,
  buildProjectStepsMarkdown,
  buildShoppingLinksJson,
  buildShoppingLinksMarkdown,
  canBuildProjectPack,
  resolveProjectAmsSlotPlan,
  shoppingLineFor,
  shoppingLinksFor,
  type ProjectPackInput,
  type ShoppingLinkStub,
} from "./project-pack";
export {
  AMS_SLOT_INDEX_MAX,
  AMS_SLOT_INDEX_MIN,
  AMS_TRAY_COUNT,
  amsSlotPlanSidecarJson,
  applyChatAmsSlotAssignment,
  buildAmsSlotPlan,
  declaredDesignFilaments,
  isAmsSlotIndex,
  isAmsSlotPlan,
  mapDesignFilamentsToAms,
  normalizeAmsSlotPlan,
  parseAmsSlotPlan,
  reassignAmsSlot,
  slotFromTrayIndex,
  trayIndexFromSlot,
  type BuildAmsSlotPlanInput,
  type ChatAmsSlotAssignment,
  type DesignFilamentLike,
} from "./ams";
export {
  MACHINE_RESHAPE_STORAGE_KEY,
  isReshapeRemainingActive,
  isReshapeRemainingEnabled,
  maybeEmergencyReshapeRemaining,
  parseReshapeRemainingPref,
  peekLastReshapePlan,
  planRemainingLayerReshape,
  rememberReshapePlan,
  resetReshapeState,
  resolveCurrentZ,
  serializeReshapeRemainingPref,
  RESUME_IS_MANUAL,
  RESHAPE_LATER_OPTION,
  type ReshapePlannerInput,
  type CadReshapeHandoff,
  type EmergencyRemainingReshapePlan,
  type ReslicePlanStub,
  type StumpCutPlaneBoundsMm,
} from "./reshape";
export {
  CAD_RESHAPE_INSTRUCTION,
  buildCadReshapeHandoff,
  buildReslicePlanStub,
  isStumpCutPlaneBoundsMm,
  resolveHandoffLayerHeightMm,
  resolveHandoffPreviousCode,
  stumpCutPlaneBoundsFromJobStl,
  stumpCutPlaneBoundsFromMesh,
} from "./reshape-plan";
