// Fixture snapshot: lightweight phone stand with honeycomb (mm).
// Generated by lib/lattice.ts phoneStandHoneycombScad(). Heuristic — not FEA.
$fn = 24;
phone_w = 76;
tilt = 60;
base_d = 78;
base_t = 12;
back_h = 90;
back_t = 12;
lip = 10;
cable = 14;
shell_mm = 1.6;
cell_mm = 8;
strut_mm = 1.6;

module lattice_voids(sx, sy, sz) {
  pitch_x = cell_mm + strut_mm;
  pitch_y = pitch_x * 0.866;
  for (iy = [0 : 1 : floor(sy / pitch_y) + 2])
    for (ix = [0 : 1 : floor(sx / pitch_x) + 2])
      translate([(ix + (iy % 2) * 0.5) * pitch_x, iy * pitch_y, -1])
        rotate([0, 0, 30])
          cylinder(h = sz + 2, d = cell_mm, $fn = 6);
}

module latticed_box(sx, sy, sz) {
  difference() {
    cube([sx, sy, sz]);
    intersection() {
      translate([shell_mm, shell_mm, shell_mm])
        cube([sx - 2 * shell_mm, sy - 2 * shell_mm, sz - 2 * shell_mm]);
      lattice_voids(sx, sy, sz);
    }
  }
}

module cable_keeper() {
  translate([phone_w / 2 - cable / 2 - shell_mm, -1, -1])
    cube([cable + 2 * shell_mm, 18 + shell_mm, base_t + 2]);
}

module stand_body() {
  union() {
    difference() {
      latticed_box(phone_w, base_d, base_t);
      cable_keeper();
    }
    translate([0, 16, base_t])
      rotate([-tilt, 0, 0])
        latticed_box(phone_w, back_t, back_h);
    translate([0, 10, base_t])
      cube([phone_w, lip, 12]);
  }
}

difference() {
  stand_body();
  translate([phone_w / 2 - cable / 2, -1, -1])
    cube([cable, 16, 20]);
}
